import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function main() {
  const transport = new StdioClientTransport({
    command: "node",
    args: [path.join(__dirname, "dist", "index.js")],
  });

  const client = new Client(
    { name: "test-client", version: "1.0.0" },
    { capabilities: {} }
  );

  try {
    await client.connect(transport);
    console.log("Connected to MCP server.");

    console.log("Calling gmail_draft_email tool...");
    const result = await client.callTool({
      name: "gmail_draft_email",
      arguments: {
        to: ["test@example.com"],
        subject: "Test Draft from MCP Server",
        body: "Hello!\n\nThis is a test draft generated by the Google Workspace MCP Server to verify that the tool works correctly.\n\nBest regards,\nMCP Agent",
      },
    });

    console.log("Tool execution result:");
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error("Failed to execute tool:", error);
    process.exit(1);
  } finally {
    await transport.close();
  }
}

main().catch(console.error);
